version: '3.4'

services:
  stefaninidb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  stefanini.api:
    image: ${DOCKER_REGISTRY-}stefaniniapi
    build:
      context: .
      dockerfile: Stefanini.API/Stefanini.API/Dockerfile

networks: 
  mssql-network:
    driver: bridge
