version: '3.4'

services:

  stefaninidb:
    container_name: stefaninidb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "5434:5434"

  