version: '3.4'

services:

  stefaninidb:
    container_name: stefaninidb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    networks:
      - mssql-network 
  
  stefanini.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:ConnectionString=Server=stefaninidb;Database=stefaninidb;User Id=sa;Password=SwN12345678"            
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - stefaninidb
    command: ["dotnet", "ef", "database update"]
    networks:
      - mssql-network